# Generated by Django 3.2.9 on 2021-12-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0002_remove_receita_tempo_preparo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='tempo_preparo',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
