# Generated by Django 3.2.9 on 2021-12-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0007_auto_20211210_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='slug',
        ),
        migrations.AddField(
            model_name='receita',
            name='id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
